global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Recipes.API'
    static_configs:
      - targets: ['recipes-api:8081']